ingress:
  path: /api/session-manager
  affinity: true

persistence:
  enabled: true

env:
  - name: SESSION_MANAGER_SECRET
    valueFrom:
      secretKeyRef:
        name: x-session-manager-api-key
        key: secret

autoscaling:
  hpa:
    enabled: false
  vpa:
    enabled: true