ingress:
  path: /api/session-manager
  
persistence:
  enabled: true

env:
  - name: SESSION_MANAGER_SECRET
    valueFrom:
      secretKeyRef:
        name: x-session-manager-api-key
        key: secret